ARG VERSION
FROM nvcr.io/nvidia/pytorch:${VERSION}

RUN pip install tqdm efficientnet_pytorch albumentations opencv-python
RUN apt update && apt-get install -y libgl1-mesa-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# For using YOLOv5
#RUN pip install -r https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt