ARG VERSION
FROM nvcr.io/nvidia/pytorch:${VERSION}

RUN pip install tqdm efficientnet_pytorch albumentations torchsummary cityscapesscripts torchmetrics
# For using YOLOv5
RUN pip install -r https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt

RUN apt update &&  \
    apt install -y libgl1-mesa-glx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*rm

RUN apt update &&  \
    apt install -y ninja-build git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*rm

RUN python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
